### ISSUE TITLE
Adicione o resto do projeto

### ISSUE THREAD

**Issue by Takeshi-mi** [LehBittencourt/ProjetoFinal#1]
Oi Letícia, por enquanto só tem o README. Adicione o restante do projeto seguindo aquele passo a passo que te mostrei ontem. Qualquer dúvida fico a disposição.

**Comment by LehBittencourt** [comment]
Oie, ontem eu estava arrumando tudo certinho só que esse deu um erro e eu não estava conseguindo colocar, acho que fiz algo errado, depois vou conferir certinho. Obrigada pela ajuda!
